image:
  file: Dockerfile

ports:
  - port: 8001
    onOpen: ignore
  - port: 8000
    onOpen: open-browser
  - port: 443
    onOpen: open-browser
  - port: 3306
    onOpen: ignore
tasks:
  - init: composer install
    command: npm install
  - name: Create_sql
    command: >
        mysql
        GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost';
        CREATE DATABASE student_portal;
        exit

        php artisan key:generate
        php artisan migrate --seed
  - name: MySQL
    command: >
        mysqld
  - name: Apache
    command: >
        apachectl start;
        multitail /var/log/apache2/error.log -I /var/log/apache2/access.log
